<a href="https://colab.research.google.com/github/Manikandan-professional/Acquisitions-by-Tech-Companies/blob/main/Acquisitions_by_Tech_Companies.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
a='https://raw.githubusercontent.com/Manikandan-professional/Datasets/main/acquisitions_update_2021.csv'
df=pd.DataFrame(pd.read_csv(a))
df

        ID  ...                                   Derived Products
0        1  ...                                                  -
1        2  ...                                                  -
2        3  ...                                                  -
3        4  ...                                                  -
4        5  ...                                                  -
...    ...  ...                                                ...
1450  1451  ...  GoToMeeting, GoToTraining, GoToWebinar, ShareF...
1451  1452  ...                                 XenApp, XenDesktop
1452  1453  ...                                 XenApp, XenDesktop
1453  1454  ...                                         Citrix ITM
1454  1455  ...                                   Citrix Workspace

[1455 rows x 10 columns]